default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: test-yourself-dev

test:
  <<: *default
  database: test-yourself-test

production:
  <<: *default
  database: test-yourself-production
